services:

    db:
        image: mysql
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: appDB
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/1.sql
        ports:
            - 8806:3306

    server:
        container_name: php-apache
        build: ./server/
        ports:
            - 8000:80
        volumes:
            - ./server/php/src:/var/www/html/
        depends_on:
            - db
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
        ports:
            - 8080:80
        depends_on:
            - db